const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
    "I loved you, I love you and I will love you forever!",
    "I'm so proud of you for doing your best to be okay.",
    "I'm so proud of you for waking up everyday and trying.",
    "You are going to get  through  whatever you're going through. ",
    "I love you",
    "I hope you know you are worthy of your wildest dreams.",
    "You are someone worth fighting for.",
    "Proud ako sayo so muchhhh joo",
    "I adore you",
    "You make my smile",
    "You have the sweetest soul I have ever seen.",
    "I want the side of you that you don't show to anyone else.",
    "If I had two hearts, I would fall for you twice.",
    "I love the feeling I get when I see you.",
    "You are my soulmate",
    "You are the stars in my dark and cold nights shining and unwavering.",
    "You are a sky full of stars",
    "Alagaan ang sarili kasi ito ang bagay na permanente",
    "MAGPAHINGA",
    "I always smile when I think about you.",
    "My safe place",
    "My home",
    "Your presence is a gift",
    "You have my heart, keep it safe",
    "You are exactly where you're supposed to be.",
    "I love you more than I did yesterday",
    "Your love is all Ill ever need",
    "Thank god I found you",
    "Sabay nating harapin ang ating mga future battles mwaaa",
    "I love you to the moon and back",
    "Andito lang ako lagi para sa iyo love",
    "No regrets, just love",
    "My dreams came true with you",
    "To me, you are perfect",
    "You are my greatest blessing",
    "You are the only exception",
    "I love you",
    "Thank you for being the person who makes people feel ok when they're not okay.",
    "The world truly is a kinder place because you are in it.",
    "I want you in my life for today, tomorrow and forever.",
    "I have fallen in love many times. But every time, it was with you!",
    "If I get paid for loving you, I would be a millionaire by now!",
    "I will love you till my last breath, no matter what life brings before us!",
    "You are the only reason why I survive; I love you so so much!",
    "The more days go, the more I fall in love with you. You are the Queen of my heart.",
    "I will be your number ONE fan",
    "If you ask me when I want to be with you, my answer will be now and forever.",
    "It's okay to have moments of doubt or fear because they're part of life.",
    "It's okay to stumble or have regrets;it's all part of the learning process.",
    "Im loving you more each and every day.",
    "Kaya mo 'yan. Kakayanin mo. I'm here to support you on your journey.",
    "My love for you isnt something that can be measured. I just know my heart is full of it.",
    "Im having one of those days that make me realize how lost Id be without you.",
    "Something made me think of you today. Now I cant stop thinking of you.",
    "No matter where I go, or what I do, Im thinking of you.",
    "VALID kaaaa!!!",
    "My soul and your soul are forever tangled.",
    "I am really blessed to have you in my life. I love you so much.",
    "It was hard to get out of bed this morning, because I just want to hold you forever.",
    "Its always better when were together.",
    "I need you like a heart needs a beat.",
    "You are the reason for my smile.",
    "You are my greatest adventure.",
    "I wish I could tell you how much I love you, but there are no words for it.",
    "Your flaws are perfect for the heart thats meant to love you.",
    "I am in you and you in me, mutual in divine love.",
    "Smile ka lang lagiiii hihi <3",
    "The world is so small compared to my love for you.",
    "I cant wait to see you again",
    "Ang ganda-ganda mooooo <33",
    "I love you and I like you",
    "I miss you",
    "You wanna know who I'm in love with? Read the first word again.",
    "I absolutely adore you. Just FYI.",
    "Stop making me think about you! I'm busy",
    "Your texts make my day even better.",
    "Come to my dreams if you can. I'll kiss you there.",
    "You make me the happiest person on Earth.",
    "Every time you text me, I get butterflies.",
    "Such a stressful day. Want to blow off some steam tonight?",
    "I love you with all my heart.",
    "I cant wait to come home to you tonight",
    "Love = you + me.",
    "Forever and always, without a doubt, I am yours.",
    "I misssss youuu so muchhhhh",
    "Wanna know something? I love you.",
    "I only saw you for a second, but it made my day.",
    "Let it be known that I love you a lot. Wherever you go, I shall follow.",
    "I want to wake up every morning with the scent of your hair!",
    "In my eyes, you are perfect. I adore you.",
    "I want to go on a world tour with my queen someday.",
    "I cant imagine living a life without you. You are my reason to be.",
    "I love you more and more with each and every passing day.",
    "May I dance with you to the tune of a song that lasts forever?",
    "You have no idea the amount of happiness you brought into my life.",
    "I love you like I love my video games. You are really so special!",
    "I would like to fill my calendars with memories of you.",
    "MAHAL KITA",
    "You are like money. The more I get, the more I want!",
    "You make me want to be a better person, just by being you.",
    "I hope to make you happy beyond belief.",
    "You tripped me, so I fell for you.",
    "You're the missing puzzle piece I never knew I needed",
    "My love for you is like a never-ending Netflix queue, always something new to discover.",
    "Can I borrow a kiss? I promise Ill give it back.",
    "I have discovered that home too has a smell. You are my home.",
    "Can't wait to hold you so tight, the world disappears.",
    "The only thing I want to be an expert at is loving you!",
    "Every atom, molecule, and cell of me loves you.",
    "Im so lucky to have you! I love you forever!",
    "Being in love with you makes every morning worth getting up for.",
    "Its just you and me against the world. I love you!",
    "My love for you is like the water in the ocean. It will never dry up.",
    "My love for you is like the ocean, deep and boundless.",
    "To the moon and back, I love you.",
    "I have many reasons to die for, but only one to live for, that is you!",
    "You stole my heart and I dont want it back ever!",
    "Thank you, my love, for making me feel like the most beautiful person in the world.",
    "I am blessed to be with a girl like you!",
    "Oki lang maging mahina ah. Iiyak mo lang huwag mo pabigatin ang pasan mo sa dibdib",
    "Its you and me against the universe. Were the strongest team there is.",
    "Hold my hand, hold my heart, and hold me forever. I love you",
    "My favorite color is the light in your eyes when you smile.",
    "Hindi mo kailangang abutin ang expectation nang kung sino man. Be yourself lang po my love.",
    "I wish you were here, or I was there, or we were together anywhere",
    "You're my sunshine on a cloudy day, the rainbow after the storm.",
    "Thank you so much jooo <3 , Happy new year and hindi ako makapag antay kung anong meron sa susunod na taon",
  ]
  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})